import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { injectAgentsMd, removeManagedSection, hasManagedSection, getUserContent } from '../../src/injector/index.js';
import { writeFile, readFile } from 'fs/promises';
import { join } from 'path';
import { mkdirSync, existsSync, rmSync, readFileSync } from 'fs';

describe('Injector', () => {
  const testDir = join(__dirname, 'test-project-injector');
  const agentsMdPath = join(testDir, 'AGENTS.md');

  beforeEach(() => {
    if (!existsSync(testDir)) {
      mkdirSync(testDir, { recursive: true });
    }
  });

  afterEach(() => {
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true });
    }
  });

  it('should inject into empty AGENTS.md', async () => {
    const indexes = [
      '[Next.js Docs Index]|root:./.agent-docs/nextjs',
      'IMPORTANT: Prefer retrieval-led reasoning'
    ];

    await injectAgentsMd(agentsMdPath, indexes);

    const content = readFileSync(agentsMdPath, 'utf-8');
    expect(content).toContain('<!-- BEGIN SKILL-COMPILER MANAGED SECTION -->');
    expect(content).toContain('<!-- END SKILL-COMPILER MANAGED SECTION -->');
    expect(content).toContain('[Next.js Docs Index]');
  });

  it('should preserve user content when injecting', async () => {
    // Create existing AGENTS.md with user content
    const userContent = '# My Project Guidelines\n\nSome custom content here.';
    await writeFile(agentsMdPath, userContent);

    const indexes = [
      '[Next.js Docs Index]|root:./.agent-docs/nextjs',
      'IMPORTANT: Prefer retrieval-led reasoning'
    ];

    await injectAgentsMd(agentsMdPath, indexes);

    const content = readFileSync(agentsMdPath, 'utf-8');
    expect(content).toContain('# My Project Guidelines');
    expect(content).toContain('Some custom content here.');
    expect(content).toContain('[Next.js Docs Index]');
  });

  it('should replace existing managed section', async () => {
    // Create AGENTS.md with existing managed section
    const existingContent = `# Project Guidelines

<!-- BEGIN SKILL-COMPILER MANAGED SECTION -->
<!-- DO NOT EDIT THIS SECTION MANUALLY - Generated by skill-compiler -->
## Framework Documentation Indexes
[Old Index]|root:./.agent-docs/old
<!-- END SKILL-COMPILER MANAGED SECTION -->`;

    await writeFile(agentsMdPath, existingContent);

    const indexes = [
      '[New Index]|root:./.agent-docs/new',
      'IMPORTANT: Prefer retrieval-led reasoning'
    ];

    await injectAgentsMd(agentsMdPath, indexes);

    const content = readFileSync(agentsMdPath, 'utf-8');
    expect(content).toContain('[New Index]');
    expect(content).not.toContain('[Old Index]');
  });

  it('should remove managed section', async () => {
    const indexes = [
      '[Next.js Docs Index]|root:./.agent-docs/nextjs',
      'IMPORTANT: Prefer retrieval-led reasoning'
    ];

    await injectAgentsMd(agentsMdPath, indexes);

    let hasSection = await hasManagedSection(agentsMdPath);
    expect(hasSection).toBe(true);

    await removeManagedSection(agentsMdPath);

    hasSection = await hasManagedSection(agentsMdPath);
    expect(hasSection).toBe(false);

    const content = readFileSync(agentsMdPath, 'utf-8');
    expect(content).not.toContain('<!-- BEGIN SKILL-COMPILER MANAGED SECTION -->');
  });

  it('should get user content', async () => {
    const userContent = '# My Project Guidelines\n\nSome custom content here.';
    await writeFile(agentsMdPath, userContent);

    const content = await getUserContent(agentsMdPath);
    expect(content).toBe(userContent);
  });
});